### ISSUE TITLE
Release of Direflow v. 2.0.0

### ISSUE THREAD

**Issue by Silind** [Silind-Software/direflow#17]
## Release of Direflow v. 2.0.0

The new release will include the following updates:
### Breaking changes:
- [x] Deprecation of 'Direflow Project' and the command `direflow create -p`.
- [x] Ability to create multiple components from the same setup. See this [PR](https://github.com/Silind-Software/direflow/pull/16).
- [x] Performance optimizations. Better usage of shared dependencies.

### Enhancements:
- [x] Isolated properties and attributes. See this [PR](https://github.com/Silind-Software/direflow/pull/13).
- [x] Registration of properties and attributes becomes optional.

### Part of 2.x.x:
- [ ] Introducing support for child elements. See this [issue](https://github.com/Silind-Software/direflow/issues/4).
- [ ] Polyfills becomes configurable through plugins. See this [issue](https://github.com/Silind-Software/direflow/issues/18)
- [ ] Doc pages on how to get started developing on Direflow, in order to make it easier for other developers to contribute with PRs. See this [issue](https://github.com/Silind-Software/direflow/issues/22)
